### ISSUE TITLE
Change of username causes sql errors

### ISSUE THREAD

**Issue by Aequitas737** [forcedotcom/SalesforceMobileSDK-ReactNative#161]
A user logged in using the mobile sdk changed their username and then received an SQLite error every time they tried to query an object:

`net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;`

**Comment by wmathurin** [comment]
What version of the mobile SDK are you using?

**Comment by Aequitas737** [comment]
7.3.0 @wmathurin

**Comment by wmathurin** [comment]
The error above happens if you access a store with the wrong key. That could happen if you application holds on to a SmartStore object after a logout took place. Instead the application should call getSmartStore() whenever it needs to interact with its store.
Does it sound like something you might be doing in your application?

**Comment by wmathurin** [comment]
My last question was never answered. Hopefully, my last response helped you solve your issue.
