### ISSUE TITLE
Missing documentation on Promises on react-native-force forceUtil methods:

### ISSUE THREAD

**Issue by AnilDeshpande** [forcedotcom/SalesforceMobileSDK-ReactNative#249]
We have been trying to find the documentation which explains us methods that can be called on forceUtil and mobilesync.
import { smartstore, mobilesync, forceUtil, net } from 'react-native-force';

Other than promiser and promiserNoRejection what other option do we have.

const registerSoup = forceUtil.promiser(smartstore.registerSoup);
const getSyncStatus = forceUtil.promiser(mobilesync.getSyncStatus);

const syncDown = forceUtil.promiserNoRejection(mobilesync.syncDown);
const syncUp = forceUtil.promiserNoRejection(mobilesync.syncUp);
const reSync = forceUtil.promiserNoRejection(mobilesync.reSync);

**Comment by wmathurin** [comment]
Those are just convenient methods that turn the Mobile SDK APIs (which are all callbacks based) into promise-based APIs. So instead of doing `method(args, onSuccess, onFailure)`, you do `promiseBasedMethod(args).then(onSuccess).catch(onFailure)`.
You have the choice: you can use the default APIs (callbacks based), use the promiser function if you prefer promises or do something else in your application.
What part would you like to see better explained?

**Comment by AnilDeshpande** [comment]
I was wondering why for mobilesync.syncDown,  mobilesync.syncUp, mobilesync.reSync, we can't use forceUtil.promiser (like we use with smartstore.registerSoup, mobilesync.getSyncStatus). 

Correct me if I am wrong, If I understand correctly with 

1. forceUtil.promise - we have both success and failure call backs
2. forceUtil.promiserNoRejection - we have only success call backs, no failure call backs 

`function syncDownAppointments(soql_query, uniqueID) {
  syncName = uniqueID;
  console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  syncName:', syncName);
  if (syncInFlight) {
    console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  Not starting syncDown - sync already in flight:');
    return Promise.resolve();
  }

  syncInFlight = true;
  const target = {
    type: 'soql',
    query: soql_query,
  };
  return syncDown(
    false,
    target,
    'serviceappointments',
    { mergeMode: mobilesync.MERGE_MODE.OVERWRITE },
    syncName
  )
    .then((res) => {
      syncInFlight = false;
      emitSmartStoreChanged();
      syncUpAppointments();
    })
    .catch((error) => console.log('TAG: Sync, FileScreen - serviceAppointmentManager.js, function: syncDownAppointments, message:  error in sync down', error)); // This error call back is not coming at all!!!
}`

**Comment by wmathurin** [comment]
You could use promiser instead of promiserNoRejection however the error callback is only invoked if there is "total failure" of the sync (e.g. could not reach server). 
If the sync runs but a few records failed to save (maybe because they are missing required field), the sync operation is still considered a success. That's the semantic we have chosen to have from the beginning.

**Comment by AnilDeshpande** [comment]
But when we use the **promiser**, we don't get any success call backs. I would prefer to the **promiser** instead of **promiserNoRejection** and I tried it as well. I was hoping to get a success call back, but I didn't.

**Comment by gkotula** [comment]
@AnilDeshpande Are you still having trouble with these methods?  Are you not getting success callbacks on sync operations with `promiser`?  That would be considered a bug.

**Comment by gkotula** [comment]
Closing due to lack of response.
