### ISSUE TITLE
'Remember me' is not working

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#290]
Hi,
User details are not remembered when we are reopening the app after user login. 

User Login (Remember me checked) --> Login success and entered into app --> Closes app and reopens --> Clicks on Logout.
and then he redirects to the login page but user details are not remembered.

**Comment by wmathurin** [comment]
The Remember Me button isn't meant to function the way you describe it. It's supposed to remember the username. This works on a mobile browser. However, within the mobile container, we have to clear cookies between sessions for a clean authentication experience since we support a matrix of types of authentication. As a result, the username will not be saved within the mobile container once you log out.

**Comment by bsrinath4839** [comment]
So, `Remember Me` doesn't store usernames in a mobile application created on top of SalesforceMobileSDK-ReactNative?
Is there any way to make it store the usernames even after the application closes and reopens or it is just some temporary storage to store usernames?

**Comment by bsrinath4839** [comment]
After completing Login and even some queries... If temporarily closes the app when there is no use.
After some time if we open to use and then logout, remember be is not showing the saved username

**Comment by gkotula** [comment]
Hi @bsrinath4839 Unfortunately, the "Remember Me" checkbox on mobile with standard authentication is problematic since the Mobile SDK has no control over that web view.  [This comment](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3389#issuecomment-847434455) is still accurate, and [we cannot guarantee full functionality of that checkbox](https://help.salesforce.com/s/articleView?id=000334867&type=1).  The docs linked in the comment thread above may help you to implement autofill using advanced authentication.
