### ISSUE TITLE
Sync StatusCode not available on any sync transactions

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-ReactNative#305]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.0
2. OS Version: latest
3. Device: all
4. Steps to reproduce: Build a react Native app and use smartstore to use offline capabilities and sync records with SF
5. Actual Behaviour: sync transaction details does not contain statusCode information for the composite API calls as per below documentation:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_allornone.htm
6. Expected Behaviour: statusCode information should be available in both successful and failed transactions.
7. Error Log:
{
    "soupName": "MeasureReading__c",
    "options": {
        "mergeMode": "LEAVE_IF_CHANGED"
    },
    "isGlobalStore": true,
    "error": "",
    "maxTimeStamp": 1670436020000,
    "_soupEntryId": 14,
    "type": "syncDown",
    "progress": 100,
    "endTime": 1670493672624,
    "target": {
        "maxBatchSize": 2000,
        "query": "select LastModifiedDate,Id from MeasureReading__c LAST_N_DAYS:30 order by LastModifiedDate",
        "idFieldName": "ExternalId__c",
        "type": "soql",
        "iOSImpl": "SFSoqlSyncDownTarget",
        "modificationDateFieldName": "LastModifiedDate"
    },
    "totalSize": 2210,
    "storeName": "dummyName",
    "startTime": 1670493667551,
    "status": "DONE",
    "name": "MeasureReading__c_syncDown"
}

**Comment by gkotula** [comment]
>Actual Behaviour: sync transaction details does not contain statusCode information for the composite API calls

Just to double check, your error log looks like a Mobile Sync status update which does not contain the Composite API responses.  Did you mean to paste the Composite API response itself?

**Comment by va1bhav** [comment]
We use sync methods(syncup, syncdown, resync..) exposed in src>react.force.mobilesync. Is there any other way we could sync and get the statusCode information from the composite API calls being made in background. @gkotula

**Comment by gkotula** [comment]
Hi @va1bhav, apologies for not responding right away.  Unfortunately, MobileSync does not have the functionality you are looking for.  It was designed before the Composite APIs were supported, and thus the Composite API `statusCode` is not exposed through the MobileSync APIs like `syncUp`.

If the `statusCode` is critical for your use-case, you would have to use the Composite APIs directly through the `react-native-force.net` module.

**Comment by RohitSyngenta** [comment]
@gkotula 
It seems that you're encountering issues with obtaining the total size and progress when performing a resync operation compared to a regular syncDown operation. The resync operation might be returning -1 as the total size and 0 for the progress while it's running.

To address this issue and achieve similar functionality for resync as you have for syncDown, you need to ensure that the resync logic correctly calculates the total size and progress. This might involve reviewing how the resync operation is implemented and ensuring that it provides accurate information about the total size of records to be synced and the progress of the operation.

If the resync operation provided by your sync framework or library doesn't inherently support tracking the total size and progress, you might need to implement custom logic to calculate these values based on the records being processed during the resync operation.

Could you provide more details or code snippets related to your resync operation so that I can assist you further in addressing this issue?
