### ISSUE TITLE
Smartsync errors not available via SmartSyncReactBridge

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/SalesforceMobileSDK-ReactNative#31]
As of version 5.1, Smartsync just reports a generic 'Sync failed' error regardless of the failure reason on both iOS and Android. By debugging runSync() in SyncManager.java on Android we are able to see the details of the error, but this doesn't help where we need to be able to distinguish between error types at run-time (e.g. a timeout where retrying the sync might help vs a validation or field visibility error that requires changes on the Salesforce end to resolve). It seems like the exception message should be available to pass through to javascript, is there a reason it isn't?

**Comment by wmathurin** [comment]
Sync will no longer fail for non-network errors. So if some of the records cannot be saved on the server for instance because of some validation errors, the sync will continue. The error returned by the server will be saved on the record in the `__last_error__` field.
After the sync runs, look for records that are still in the dirty state (meaning they have the `__local__` flag still set to 1), check their `__last_error__` field to make send of what happens.

Here are the PRs that are bringing this enhancement: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2528
https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1696

It will be in our next release (6.2).
