### ISSUE TITLE
White screen on login 

### ISSUE THREAD

**Issue by isaac-israel-aquant** [forcedotcom/SalesforceMobileSDK-ReactNative#317]
Please fill out the following details:

Version of Mobile SDK Used:
v. 10.0.0
Issue found in Native App or Hybrid App:
At Hybrid App (React Native)
OS Version:
API 33
Device:
Pixel 3A
Steps to reproduce:
Logout
On the login screen put the app in the background
Click on the app icon to open it
Actual behavior:
After login, the app does not navigate to the home screen (The screen that should appear after login )
Expected Behavior:
After login, the app does navigate to the home screen

**Comment by isaac-israel-aquant** [comment]
Hey @brandonpage  for me I have experience in both release and debug.  Maybe It is something how to use on React. I don't know 🤷‍♀️

**Comment by isaac-israel-aquant** [comment]
Hey, @brandonpage  do you guys. have any updates about it?

**Comment by isaac-israel-aquant** [comment]
Hey @paultiarks  or @brandonpage, do we have any updates regarding this?

**Comment by JohnsonEricAtSalesforce** [comment]
@isaac-israel-aquant - Along with @brandonpage, I'm also helping to triage this issue.  Thanks for your patience!

**Comment by JohnsonEricAtSalesforce** [comment]
@isaac-israel-aquant - We've identified an issue in the use case that's certainly similar to what you've reported, but does have a slightly different symptom.  In our test, the app finishes unexpectedly to Android's home screen rather than showing a white screen.

The fix above should be released with Salesforce Mobile SDK for Android 11.0 soon.

Could you produce a sharable skeleton app that demonstrates this "white screen" behavior and share it somehow for our testing? That would a great way to verify if the two issues really are the same.

**Comment by wmathurin** [comment]
The fix discussed above is part of the recently released Mobile SDK 11.0. Please give it a try and re-open an issue if you are still having a problem.
