### ISSUE TITLE
Callback on oauth.authenticate never getting called

### ISSUE THREAD

**Issue by dborstelmann** [forcedotcom/SalesforceMobileSDK-ReactNative#33]
```
        oauth.getAuthCredentials(
            () => that.fetchData(), // already logged in, gets called after login because app refreshes and sees it's logged in
            () => {
                oauth.authenticate(
                    () => that.fetchData(), // NEVER CALLED
                    (error) => console.log('Failed to authenticate:' + error)
                );
            });
```

The success callback passed to authenticate does not ever get called.  The app authenticates, then reloads and calls oauth.getAuthCredentials which succeeds and calls the success callback.  We are trying to run code after log in but not every time the app loads.  Please let us know if something is wrong or that there is a bug!

**Comment by wmathurin** [comment]
Do you have authenticate-at-launch set to false/no?
Otherwise the app will authenticate before loading the react native code and getAuthCredentials will always succeed (so its error callback will never be invoked).

On iOS, it's set [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m#L54) and on Android, it's set [there](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/android/app/src/main/java/com/salesforce/reactnativetemplate/MainActivity.java#L40).

**Comment by dborstelmann** [comment]
@wmathurin It's set to False/NO and it does hit our code before we call auth.  It's purely the function from oauth not getting called at the end.  What you said was the first thing I checked.

**Comment by wmathurin** [comment]
What version of the Mobile SDK are you using?

**Comment by dborstelmann** [comment]
5.2 @wmathurin

**Comment by dborstelmann** [comment]
@wmathurin We installed using the template.  The code pasted above is right out of the template.

**Comment by wmathurin** [comment]
Last question, are you having the issue on iOS, Android or both?

**Comment by dborstelmann** [comment]
@wmathurin iOS, I have not tried it on Android.  Thanks for the fast response.

**Comment by dborstelmann** [comment]
@wmathurin We are needing this because the app is occasionally forcing logouts without us calling `oauth.logout()` but not removing the soups from SmartStore when this happens.  The soups are supposed to be deleted on logout automatically by the SDK.  When we log back in after a forced logout, the soups exist because they did not get deleted on that forced logout for some reason.  Therefore, we see they exist and try to call reSync which never completes.  It doesn't fail or succeed, it just never completes.  This only happens after this forced logout state does something to the smartstore soups.  If we delete the soups manually and try again by performing syncDown rather than reSync, everything works fine again.  But to do that we need to catch login to delete the soups and sync down again on login, hence where we arrive at the above problem.

By the way, we have a fully functional app using smartsync, smartstore, and oauth that works very well almost all of the time.  The only issue is these random logouts. If you have any ideas on that as well we would love to hear them (we have refresh tokens and access tokens expire every 24 hours so theoretically this should never happen).  But in the interest of making our app always work if something happens, we still always want to be able to catch that first login, not just whether it's logged in or not, especially for UI reasons and the above problem.

**Comment by wmathurin** [comment]
Did I read you right - your refresh token are set to expire in 24 hours?

**Comment by dborstelmann** [comment]
@wmathurin No, refresh should never expire or however that works.  Access expires at 24 hours.  With regards to the original problem, this is only iOS, Android is working.

**Comment by dborstelmann** [comment]
We have seen the app stay logged in for 5 days with no logout.  But sometimes it logs out after 2 hours too.  We are all using different accounts to dev with so the issue of 5 logins on the same account invalidating the refresh token does not apply as far as I'm aware.

**Comment by wmathurin** [comment]
And the tokens are not being revoked by an admin I assume?

**Comment by dborstelmann** [comment]
No they are not @wmathurin

**Comment by wmathurin** [comment]
So you are describing possibly three issues:
1) random logouts
2) improper cleanup of smartstore following random logout
3) authenticate success callback not called after login flow

And 3) also only happens following a "random" logout, right?

**Comment by dborstelmann** [comment]
No, 3 always happens no matter what (only on iOS), it just doesn't cause us issues except when 2 happens.  If 3 happens after a fresh load, it's not a big deal because the app never got into the weird state so it syncs fine.  3 happening stops us from clearing the soups manually following 2 which follows 1.  Thanks for working with me on this. @wmathurin

**Comment by wmathurin** [comment]
Thanks for all the information. We will investigate.

**Comment by dborstelmann** [comment]
No problem.  Thank you!

**Comment by wmathurin** [comment]
On iOS, getAuthCredentials ends up calling authenticate if one is not already authenticated.
See [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceReact/SalesforceReact/Classes/SFOauthReactBridge.m#L104).

(Unfortunately - the behavior is different on Android at this point - see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java#L225).

 So
``` javascript
oauth.getAuthCredentials(
            () => place1 // you should get here if login succeeds or if already login
            () => {
                place2 // if you get here, then authentication failed - so oauth.authenticate will probably fail and therefore you will not get to place3 but you should get to place4
                oauth.authenticate(
                    () => place3
                    (error) => place4
                );
            });
```
Are you getting to place2 instead of place1, and then always end up at place4, or is something else happening?

**Comment by dborstelmann** [comment]
@wmathurin Very interesting.  Okay, so we are only ever getting to place 1 (I haven't tried failing logging in so we never get to place 2).  I assumed oauth.authenticate() was getting called but it's not.  We get to place 1 when you have good credentials.  You never get to place 2 ever, because instead of going to place 2 it goes automatically to login when credentials are bad which then goes back to place 1 when it succeeds.  And there is no difference in the object returned to getAuthCredentials.  So does this mean there is no way to see whether you have logged in for the first time or not without caching it yourself?

**Comment by wmathurin** [comment]
Correct, because getAuthCredentials automatically calls authenticate if not logged in (on iOS), it can't be used to see if one has already logged in. We will probably change that behavior in our next major release to line up iOS and Android and only return the auth credentials as the method name implies.

**Comment by dborstelmann** [comment]
Sounds good thanks for the help 👍 We will look forward to that and cache it in the meantime

**Comment by dborstelmann** [comment]
@wmathurin Because there is actually no way of knowing that the credentials failed, we are going to write a post install script to change that one line of the SDK.  So we are very much looking forwards to this being solved!

**Comment by wmathurin** [comment]
You do not need a post install script.
Fork the SalesforceMobileSDK-iOS repo, make your changes there and then edit your package.json to point to your repo instead of the forcedotcom/SalesforceMobileSDK-iOS repo.

The portion of the package.json to edit looks like
```
 "sdkDependencies": {
        "salesforcemobilesdk-android": "https://github.com/forcedotcom/SalesforceMobileSDK-Android.git#v5.2.0",
        "salesforcemobilesdk-ios": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.2.0"
    },
```
Also bring over and run the following file `https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/installios.js` to refetch the Mobile SDK and other dependencies.

**Comment by wmathurin** [comment]
Of course, you want to fork at the v5.2.0 tag. Let me know if you run into any blockers.

**Comment by dborstelmann** [comment]
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2166

@wmathurin Thanks for the suggestion but I already got this working this morning: ```execSync("sed -i '' -e 's/\\[self authenticate:nil callback:callback\\]/\\[self sendNotAuthenticatedError:callback\\]/g' ./mobile_sdk/salesforcemobilesdk-ios/libs/SalesforceReact/SalesforceReact/Classes/SFOauthReactBridge.m");
``` in `installios.js`

We are in a hosted enterprise environment in our actual app code, I don't really want to create more repos there.  Thanks for the help though, I made a PR linked above to fix it if you guys can use it.

**Comment by wmathurin** [comment]
Thanks for your contribution. It will be in the next release. So closing this issue now.
