### ISSUE TITLE
Credential are not saving even after i have check 'Remember me Button'

### ISSUE THREAD

**Issue by jais-shivam** [forcedotcom/SalesforceMobileSDK-ReactNative#335]
While login when I tick the "Remember me" button even after that Credentials are not saved after logout. 

![image](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/assets/47588402/5bf461e6-a1ca-483c-9f5a-2ddce6c5adac)

**Comment by wmathurin** [comment]
Unfortunately, the "Remember Me" checkbox on mobile with standard authentication is problematic since the Mobile SDK has no control over that web view.  [This comment](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3389#issuecomment-847434455) is still accurate, and [we cannot guarantee full functionality of that checkbox](https://help.salesforce.com/s/articleView?id=000334867&type=1).  The docs linked in the comment thread above may help you to implement autofill using advanced authentication.
