### ISSUE TITLE
Question: How to provide show password option on login page

### ISSUE THREAD

**Issue by AnuragTiwari1** [forcedotcom/SalesforceMobileSDK-ReactNative#364]
Hi, recently Microsoft edge is providing view password option for input with type="password" which is getting popular with our web users. I want to know how can we extend this to our Mobile App which is built using Salesforce Mobile SDK - React Native.

As SDK controls the web view there is no option for me to inject js.

Please guide me to implement this

**Comment by wmathurin** [comment]
You should try using advanced authentication so that login happens in native browser instead of the embedded web view.
We expose an API on Android to specify the browser to use - in your case you would specify Edge.
For more information see: https://developer.salesforce.com/docs/platform/mobile-sdk/guide/auth-android-advanced.html

**Comment by wmathurin** [comment]
Closing - re-open if my comment was not helpful.
