### ISSUE TITLE
SyncDowns/Ups on Parent Child?

### ISSUE THREAD

**Issue by mstohr1975** [forcedotcom/SalesforceMobileSDK-ReactNative#387]
Hi there,

How can I trigger initial syncDown and syncUp for syncs defined in usersyncs.json, particularly parent child ones?
We did not find an example to call syncDown passing the right target and options without defining them again, but use the definition from usersyncs.json. Any examples synching multiple children?

**Comment by wmathurin** [comment]
Our MobileSyncExplorerReactNative template demonstrates how to invoke sync downs and sync ups in a React Native application. See this class in particular: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/MobileSyncExplorerReactNative/js/StoreMgr.js

It does not use parent sync down and sync up, but the calls would be very similar.

**Comment by wmathurin** [comment]
There are two ways to run a sync.
- you can call `syncDown` or `syncUp` and pass the definition of the sync in the call.
- you can call `reSync` and pass the id or name of the sync. 

On the first run, reSync performs a full sync. In subsequent syncs, reSync returns the delta between the last run and the current state.

**Comment by wmathurin** [comment]
We recommend you use `reSync()` instead of `syncDown()` or `syncUp()`. 
`syncDown()` and `syncUp()` create new syncs every time there are call and also do full syncs.
`reSync()` can be used to do both sync down operations and sync up operations. 
It will also do incremental synching if the full sync was previously run.
The sync needs to be have been defined before hand, either programmatically or by using the config file.
