### ISSUE TITLE
Can we update react native to 0.45.1?

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-ReactNative#46]
I saw the latest commit message mentioned upgrading to RN0.45.1

But in the template repository, the react native project is still using 0.43.1

Could you advise if we could upgrade to 0.45.1 manually?

**Comment by wmathurin** [comment]
We reverted back to 0.43.1 with this [pull request](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/28).
There were issues with 0.45 on iOS, we hope to upgrade to 0.50 for our next release 6.0 (#safeharbor).

To use a different version of React Native, you need to modify your package.json which should look something like [that](https://github.com/forcedotcom/SmartSyncExplorerReactNative/blob/master/package.json).
* change the react related dependencies and devDependencies to the appropriate versions
* change the sdkDependencies to your forks (at least for Android, because you need to change the SalesforceReact gradle file [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/build.gradle#L18)) 

Of course since we tested only with 0.43.1, some things might not compile or run properly and so more changes might be required.

**Comment by daraselia** [comment]
When do you plan to release 6.0?

**Comment by wmathurin** [comment]
Before the end of the year (#safeharbor).

**Comment by wmathurin** [comment]
It's coming to our next release. (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/51).
